---
output:
  pdf_document:
    latex_engine: xelatex
    template: rap-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Juan Manuel Vazquez
orcid: "orcid.org/0000-0002-8341-2390"
jobtitle: "K99 Postdoctoral Fellow - Sudmant Lab · University of California, Berkeley"
address: "4111 Valley Life Sciences MC3140 · Berkeley · CA 94720-3140"
fontawesome: yes
email: juan@vazquez.bio
github: docmanny
twitter: TheMainManManny
linkedin: juanvazquezbio
#phone: "+1 555 5555"
web: 'vazquez.bio'
updated: yes

keywords: aging, stress response, Peto's Paradox, comparative biology, functional genomics, R, Python, molecular biology, bats, elephants, whales, open science, diversity and inclusion

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# RESEARCH INTERESTS \hrulefill

From prokaryotes to mammals, lifespan is one of the most diverse and omniprescent life history traits. Aging is both implicated in and affected by a number of biological processes at all scales of life; yet our understanding of the genetics and directionality of aging-associated traits is limited in scope. The advent of cost-effective genomics at tree-of-life scale has enabled new frontiers in the study of aging and aging-associated traits using functional and comparative biology. My work focuses on tackling interdisciplinary questions aging with equally interdisciplinary approaches, ranging from cellular and molecular biology to comparative evolutionary genomics and population genetics. I have developed a system for studying the evolution of longevity-associated traits in bats using modern functional genomics by generating chromosome-scale reference genomes and over 200 primary cell lines for over 10 species of closely-related bats with a diversity of lifespans. This system will enable us to not only identify genes and regulatory pathways associated with the evolution of increased or decreased longevity; but also understand how the mechanisms behind these findings in a native context. 


# EDUCATION \hrulefill

_University of Chicago_, Ph.D. Human Genetics \hfill __2015 - 2020__  
_University of Chicago_, M.sc. Human Genetics \hfill __2015 - 2020__

> Laboratory of: Vincent J Lynch, Department of Human Genetics  
> ___Department of Human Genetics "Thesis of the Year Award 2020"___  
> Dissertation title: _The Role of Gene Duplicates in Resolving Peto's Paradox in_ Afrotheria _and_ Chiroptera.  
> Committee Members: Marcelo Nobrega, Joseph Thorton, Yang Li, Vincent J Lynch, Yoav Gilad  

_University of Rochester_, B.S. Biology, Molecular Genetics \hfill __2011 - 2015__

_University of Rochester_, B.A. Chemistry \hfill __2011 - 2015__


# RESEARCH EXPERIENCE \hrulefill

_Postdoctoral Researcher_, Peter H Sudmant, \hfill __2020 - Present__  
University of California-Berkeley

> Focus 1: Evolution of longevity-associated traits in Californian bats. Generating chromosome-level genomes, primary cell library for >200 individuals, and phased population genetic data from 9 species of *Myotis*.  
> Focus 2: Fidelity of chromatin structure in muscle aging at the single cell level. Using multiplexed single-cell ATAC + gene expression in a trio of mouse strains.

_Ph.D. Candidate_, Vincent J Lynch, University of Chicago \hfill __2016 - 2020__

> Thesis title: "The Role of Gene Duplication in Mediating Peto's Paradox in _Afrotheria_ and _Chiroptera_"  
> Functional Genomics and Cell Biology in African Elephant (_Loxodonta africana_), the Bowhead Whale (_Balaena mysticetus_), and the Little Brown Bat (_Myotis lucifugus_).

_Rotation_, Alex Ruthenberg, University of Chicago \hfill __Summer 2016__

> Optimized Internally Calibrated ChIP (ICeChip) in _C. elegans_ to study H3K4me3 patterns at the onset of sexual maturity.

_Research Assistant_, Vera Gorbunova and Andrei Seluanov, \hfill __January 2014 - __  
University of Rochester \hfill __May 2015__

> Oxidative stress tolerance across rodents using primary fibroblasts; the effects of SIRT6-knockouts on cell growth and tumorigenesis; self-assembled hydrogels using Naked Mole Rat-derived hyaluronic acid and their use in cancer and pluripotent stem cells; and the molecular mechanism of hyaluronic acid-mediated cancer resistance in the Naked Mole Rat (_Heterocephalus glaber_).  

# SCHOLARSHIP \hrulefill

## Journal Articles

_\* indicates equal contribution_; ___^†^__ indicates senior author_

1. Ali N\*, Amelkina O\*, Santymire RM, Koepfli KP, Comizzoli P & __Vazquez JM^†^__ (2024). "Semen proteome and transcriptome of the endangered black-footed ferret (_Mustela nigripes_) show association with the environment and fertility outcome." _Scientific Reports_, 10.1038/s41598-024-57096-w.

1. Capel S, Hamilton NM, Fraser D, Escalona M, Nguyen O, Sacco S, Sahasrabudhe R, Seligmann W, __Vazquez JM__, Sudmant PH, Morison ML, Wayne R, Buchalski MR (2024). "Reference genome of Townsend’s big-eared bat, _Corynorhinus townsendii_." _Journal of Heredity_, 10.1093/jhered/esad078.

1.  Allen KA, Torres-Velarde JM, __Vazquez JM__, Moreno-Santillan DD, Sudmant PH, Vazquez-Medina JP (2024). "Hypoxia blunts angiogenic signaling and upregulates the antioxidant system in elephant seal endothelial cells." _BMC Biology_, 10.1186/s12915-024-01892-3.

1. Curti J, Fraser D, Escalona M, Fairbairn CW, Sacco S, Sahasrabudhe R, Nguyen O, Seligmann W, Sudmant PH, Toffelmier E, __Vazquez JM__, Wayne R, Shaffer HB, Buchalski MR (2023). "A genome assembly of the Yuma myotis bat, _Myotis yumanensis_." _Journal of Heredity_, 10.1093/jhered/esad053.

1. Karin BR, Arellano S, Wang L, Walzer K, Pomerantz A, __Vazquez JM__, Chatla K, Sudmant PH, Bach BH, Smith LL, McGuire JA (2023). "Highly-multiplexed and efficient long-amplicon PacBio and Nanopore sequencing of hundreds of full mitochondrial genomes." _BMC Genomics_, 10.1186/s12864-023-09277-6.

1. Lauterbur ME, Cavassim Alves MI, Gladstein AL, Gower G, Pope NS, Tsambos G, Adrion J, Belsare S, Biddanda A, Caudill V, Cury J, Echevarria I, Haller BC, Hasan AR, Huang X, Iasi LNM, Noskova E, Obšteter J, Corrêa Pavinato VA, Pearson A, Peede D, Perez MF, Rodrigues MF, Smith CCR, Spence JP, Teterina A, Tittes S, Unneberg P, __Vazquez JM__, Waples RK, Wohns AW, Wong Y, Baumdicker F, Cartwright RA, Gorjanc G, Gutenkunst RN, Kelleher J, Kern AD, Ragsdale AP, Ralph PL, Schrider DR, Gronau I (2023). "Expanding the stdpopsim species catalog, and lessons learned for realistic genome simulations." _eLife_, 10.7554/eLife.84874.1.

1. __Vazquez JM__, Kraft M, Lynch VJ (2022). "A CDKN2C retroduplication in Bowhead whales is associated with the evolution of extremely long lifespans and alerted cell cycle dynamics." _bioRxiv_, 10.1101/2022.09.07.506958.
  
1. __Vazquez JM__, Pena MT, Muhammad B, Kraft M, Adams LB, Lynch VJ (2022). "Parallel evolution of reduced cancer risk and tumor suppressor duplications in Xenarthra." _eLife_, 10.7554/eLife.82558.

1. Yamamoto R\*, Chung R\*, __Vazquez JM__, Sheng H, Steinberg P, Ioannidis NM, Sudmant PH (2021). "Tissue-specific impacts of aging and genetics on gene expression patterns in humans." _Nature Communications_, 10.1038/s41467-022-33509-0.

1. Kolora SRR\*, Owens GL\*, __Vazquez JM__, Stubbs A, Chatla K, Jainese C, Seeto K, McCrea M, Sandel MW, Vianna JA, Maslenikov K, Bachtrog D, Orr JW, Love M, Sudmant PH (2021). "Origins and evolution of extreme lifespan in Pacific Ocean rockfishes." _Science_, 10.1126/science.abg5332.

1. Glaberman S, Bulls SE, __Vazquez JM__, Chiari Y, Lynch VJ (2021). "Concurrent evolution of anti-aging gene duplications and cellular phenotypes in long-lived turtles." _Genome Biology and Evolution_, 10.1093/gbe/evab244.

1. __Vazquez JM__, and Lynch VJ (2021). “Pervasive Duplication of Tumor Suppressors in Afrotherians during the Evolution of Large Bodies and Reduced Cancer Risk.” _eLife_, 2021;10:e65041.

1. __Vazquez JM__, Sulak M, Chigurupati S, Lynch VJ (2018). “A Zombie LIF Gene in Elephants Is Upregulated by TP53 to Induce Apoptosis in Response to DNA Damage.” _Cell Reports_, 24(7), 1765-1776.  

1. Patrick A, Seluanov M, Hwang C, Tam J, Khan T, Morgenstern A, Wiener L, __Vazquez JM__, Zafar H, Wen R, Muratkalyeva M, Doerig K, Zagorulya M, Cole L, Catalano S, Ladd A, Coppi A, Coşkun Y, Tian, X, Ablaeva J, Nevo E, Gladyshev V, Zhang Z, Vijg J, Seluanov A, Gorbunova V (2016). “Sensitivity of primary fibroblasts in culture to atmospheric oxygen does not correlate with species lifespan.”, _Aging_, 8 (5), 841-847.  

## Reviews

1. Li S, __Vazquez JM__, Sudmant PH (2023). "The Evolution of Aging and Lifespan." _Trends in Genetics_ 10.1016/j.tig.2023.08.005.

<!--
## Manuscripts in Review

-->

## Accepted Manuscripts

1. __Vazquez JM__, Khudyakov J, Madelaire CB, Godard-Codding CA, Lam EK, Piotrowski E, Merrill GB, Routti H, Conner J, Wisse J,Allen KN, Blevin P, Spyropoulos DD, Goksøyr A and Vazquez-Medina JP (2024). "_Ex vivo_ and _In vitro_ Methods as a Platform for Studying Anthropogenic Effects on Marine Mammals: Four challenges and how to meet them." _Frontiers in Marine Science_.

## Manuscripts in Preparation

1. _ETA: September 2024_\hfill__Vazquez JM__, Lauterbur ME, Mottaghinia S, Bucci M, Fraser D, Gray-Sandoval G, Haidar ZR, Kohler W, Lama T, LeCorf A, Maesen S, McMillan D, Lo J, Miller R, Rey C, Singer M, Slocum K, Thomas W, Tyburek J, Buchalski M, Etienne L, Enard D, Sudmant PH. "Extensive longevity and DNA virus-driven adaptation in nearctic Myotis."

1. _ETA: September 2024_\hfill Le Corf A, Maesen S, Loyer C, __Vazquez JM__, Lauterbur M, Grey-Sandoval G, Cimarelli A, Rey C, Sudmant PH, Enard D, Etienne L. "Genomic and functional adaptations in guanylate-binding protein 5 (GBP5) highlight specificities of bat antiviral innate immunity."

## Invited Talks

Stanford-Berkeley-UCSF Next-Generation Faculty Symposium. _Uncovering novel pathways to longevity by studying lifespan at its extremes_. 17 November 2023, Virtual.

École Normale Supérieure de Lyon, Molecular Evolution Seminar Series. __A CDKN2C retroduplication in Bowhead whales is associated with the evolution of extremely long lifespans and alerted cell cycle dynamics__. 11 July 2023.

North American Society for Bat Research. _Bat to the Future: Bat Biology Beyond Genomes._ 07 August 2022, Austin, TX, USA.

Stanford University, _Resolving the Evolution of Longevity and Associated Traits in Bats Using Functional and Population Genomics_, 13 June 2022.

## Oral Presentations  

Biodiversity Genomics Conference. _Evolution of non-allometric longevity and anti-viral immunity in nine Neartic_ Myotis _species revealed using chromosome-scale genome assemblies_. 3 October 2023,  Virtual (International).

Marine Mammal Symposium, University of California-Berkeley. _A CDKN2C retroduplication in Bowhead whales is associated with the evolution of extremely long lifespans and alerted cell cycle dynamics_. 25 May 2023, Berkeley, CA, USA.

Bay Area Aging Meeting. _Evolution of Non-Allometric Longevity in a Clade of Long-Lived Bats Resolved Using Chromosome-Length Genome Assemblies_. 11 May 2023, Novato, CA, USA

UCB Center for Computation Biology Retreat. _Building a Model System for Studying the Evolution of Extraordinary Longevity in Bats Using Functional Genomics._ 05 November 2022, Green Mountain Retreat, CA, USA.

Biodiverse Genomes Conference. _Evolution of Non-Allometric Longevity in a Clade of Long-Lived Bats Resolved Using Chromosome-Length Genome Assemblies._ 12 September 2022, Virtual (International).

International Society for Evolutionary Medicine and Public Health. _Evolution of Non-Allometric Longevity in a Clade of Long-Lived Bats Resolved Using Chromosome-Length Genome Assemblies._ 07 July 2022, Lisbon, Portugal.

eLife Evolutionary Medicine Symposium. _Of Mice and Elephants: Trade-Offs of Tumor Suppressor Duplication and Body Size Evolution in Afrotheria._ 13 December 2021, Virtual (International).

American Aging Associate (AGE) Meeting. _A Novel Model System for the Study of Evolution of Longevity and Longevity-Associated Traits Using Western Bats._ 20 July 2021, Madison, WI, USA.

Club EvMed: Virtual Evolutionary Medicine Conversations. _Of Mice and Elephants: Trade-Offs of Tumor Suppressor Duplication and Body Size Evolution in Afrotheria._ 29 June 2021, Virtual (International).

Bat1K Battelite Meeting. _Western Bat Genomes Project._ 20 May 2021, Virtual (International).

Puerto Rico Virtual Research Talks. _Como crecen los elefantes: La evolución de resistencia al cáncer en mamíferos gigantes._ 18 February 2021, Virtual (International). 

Aging Science in Isolation Talk Series. _Gene Duplication and Peto's Paradox in Afrotherians._ 19 May 2020, Virtual (International).  

North American Society for Bat Research. _Stress Response and a P53 Duplication in the Long-Lived Bat,_ Myotis lucifugus. 24 October 2019, Kalamazoo, MI, USA.  

Biology of Aging Gordon Research Conference. _Stress Response and a P53 Duplication in the Long-Lived Bat,_ Myotis lucifugus. 16 July 2019, Sunday River, MA, USA.  

## __Poster Presentations__  

Biology of Aging Gordon Research Conference. __Vazquez JM__, Lauterbur ME, Fraser D, Buchalski M, Enard D, Sudmant PH. "A Model System for Studying the Evolution of Longevity-Associated Traits Using Functional Genomics." 01 - 07 July 2023, Castelldefels, Catalonia, Spain.

Systems Biology of Aging Gordon Research Conference. __Vazquez JM__, Lauterbur ME, Fraser D, Buchalski M, Enard D, Sudmant PH. "A Model System for Studying the Evolution of Longevity-Associated Traits Using Functional Genomics." 29 May - 03 June 2022, Sunday River, MA, USA.

Biology of Genomes. __Vazquez JM__, Lauterbur ME, Fraser D, Buchalski M, Enard D, Sudmant PH. "A Model System for Studying the Evolution of Longevity-Associated Traits Using Functional Genomics." 10-14 May 2022, Cold Spring Harbor, NY, USA.

NDiSTEM. __Vazquez JM__, Lynch VJ. "Gene Duplications and Peto's Paradox in the African Elephant and Paenungulates." 12 October 2018, San Antonio, TX, USA.  

Biology of Aging Gordon Research Seminar and Conference. __Vazquez JM__, Lynch VJ. "A Role for Gene Duplication in Peto's Paradox." 8-14 July 2017, Les Diablerets, CH.  


# FUNDING, AWARDS, AND FELLOWSHIPS \hrulefill

## __Fellowships, Scholarships, and Training Grants__

__NIH K99/R00 MOSAIC (1K99AG088361)__ \hfill __2024 - 2026__

__NIA T32 Trainee__ \hfill __2023 - 2024__

> NIH \hfill R13AG063483-01

__NSF Postdoctoral Research Fellowship in Biology (#2109915)__. \hfill __2021 - 2023__

_A Novel Model System for Studying the Evolution and Genomics of Longevity_

__Life Sciences Research Foundation Postdoctoral Fellowship.__ \hfill __2020__  
\hfill __Finalist__, unfunded (no sponsors).

__NSF Postdoctoral Research Fellowship in Biology.__ \hfill __2020__  
\hfill __Meritorious__, unfunded.

__Yale Ciencia Academy Fellowship__, \hfill __2019__  
Yale University  

__NIGMS R25 Trainee: Initiative to Maximize Student Development __, \hfill __2015 - 2017__  
University of Chicago \hfill 5R25GM109439-03

__Howard Bryant Memorial Scholarship__, \hfill __2012 - 2014__  
University of Rochester

__Dean's Scholarship__, \hfill __2011 - 2015__  
University of Rochester

## __Grants__  

__NIA U-13 Supplement, 2019 Biology of Aging Gordon Research Conference__, \hfill __2019__  
NIA R13AG063483-01. \hfill $13,757.11

__Diversity and Inclusion Pilot Program Grant__, \hfill __2019__  
University of Chicago. \hfill $5,000.00

__Diversity and Inclusion Small Projects Grant__, \hfill __2019__  
University of Chicago. \hfill $2,000.00

__Diversity and Inclusion Pilot Program Grant__, \hfill __2018__  
University of Chicago. \hfill $10,000.00

__Diversity and Inclusion Small Projects Grant__, \hfill __2018__  
University of Chicago. \hfill $2,000.00


## __Awards and Recognitions__

__2022 Best Lighting Talk__. UCB Center for Computational Biology Retreat. \hfill __2022__

__2021 Trainee Diversity, Equity, and Inclusion Legacy Award__. University of Chicago \hfill __2021__

__SACNAS Chapter of the Year Award__, \hfill __2019__  
Society for the Advancement of Chicanos/Hispanics and Native Americans in Science (SACNAS).

> The Chapter of the Year Award is presented to the SACNAS chapter which demonstrates exceptional leadership and aptitude in chapter development, professional development, recruiment and membership, community outreach, and fundraising.   

__SACNAS Chapter Role Model Award for Outstanding Professional Development__, \hfill __2018__  
Society for the Advancement of Chicanos/Hispanics and Native Americans in Science (SACNAS).

> In recognition of the UChicago SACNAS Chapter's exceptional work in organizing and executing the first-ever Midwest Regional SACNAS Conference.  


# PROFESSIONAL ACTIVITIES \hrulefill

## Peer Review

__Reviewer__, Scientific Data \hfill 2023 - Present

__Review Editor__, Frontiers in Aging, Genomics and Epigenomics of Aging Section \hfill 2021 - Present

__Reviewer__, Gene \hfill 2021 - Present

__Reviewer__, Yale Ciencia Academy Fellowship \hfill 2020 - Present


## __Conferences__

__Discussion Leader__, Gordon Research Seminar - Biology of Aging, Castelldefels, Catalonia, Spain \hfill 2023

> Session: Mentorship and Career Development

__Chair__, Gordon Research Seminar - Biology of Aging, Sunday River, MA, USA. \hfill __2017 - 2019__

> Co-chair: Victor Bustos.  
> Funded by NIA R13AG063483-01

__Chair__, Midwest Regional SACNAS Conference, Chicago, IL, USA. \hfill __2019__

> A full-day, 200-person, free conference with multiple panels, workshops, student speakers, poster session, and keynote address; target audience is underrepresented groups in STEM and STEM-allied fields.  
> Lead a team of 5 co-chairs.  
> Raised $14,000 for conference expenses, with $2000 of travel funding for attendees.  

__Co-chair__, Inaugural Midwest Regional SACNAS Conference, Chicago, IL, USA. \hfill __2018__

> A full-day, 220-person, free conference with multiple panels, workshops, student speakers, poster session, and keynote address; target audience is underrepresented groups in STEM and STEM-allied fields.  
> One of 5 co-chairs working with Conference Chair.  
> Raised $16,000 for conference expenses, with $2500 of travel funding for attendees.  

## __Organizations__

__Co-Lead__, Marine Mammal Research Collaborative Network. \hfill __2023 - Present__

__Project Co-Lead__, Bat1K: Longevity and Aging Working Group.\hfill __2023 - Present__

__Working Group Leader__, GBatNet: "How Old is this Bat" Methylation Aging Working Group. \hfill __2022 - Present__

__Regional Chair__, Bat1K: Western North America.\hfill __2021 - Present__

__President__, \hfill __2018 - 2020__  
Society for the Advancement of Chicanos and Native Americans in Science, University of Chicago.

> Received the SACNAS National Chapter of the Year Award.  
> Led the 2019 Midwest Regional SACNAS Conference Planning Team.  
> Established the SACNAS Midwest Meeting Planning Commmittee for facilitating inter-chapter communication, organization, and conference planning.  

__Treasurer__, \hfill __2017 - 2018__  
Society for the Advancement of Chicanos and Native Americans in Science, University of Chicago.

__Student Representative__, \hfill __2017 - 2018__  
Deparment of Human Genetics, University of Chicago.

## __Committees__

__Member__, AGE Trainee Chapter: Diversity, Equity, Inclusion, and Outreach Committee. \hfill __2020 - 2022__

__Member__, AGE Trainee Chapter: Grants, Meetings, and Opportunities Committee Member. \hfill __2020 - 2022__

__Member__, Biological Sciences Division Diversity & Inclusion Representative Selection Committee, University of Chicago. \hfill __2017 - 2018__

__Board Member__, Community Service Fund, Student Government, University of Chicago. \hfill __2015 - 2016__

## __Panels and Presentations__

__Panelist__, "How to be an Effective Student Leader", Midwest Regional SACNAS Conference, Chicago, IL.  \hfill __April 2019__

> Part of a larger talk on how to start-up and lead an organization, panelists consisted of student leaders from across the Midwest answering questions from attendees.  

__Panelist__, "How to Succeed in Grad School", Summer Graduate Research Program, University of Chicago.  \hfill __August 2018__

> Panel focused on the experiences of panelists as underrepresented minorities in STEM, and how they navigated life through their PhDs. Panelists shared their advice and stories about how they overcame various obstacles in academia.  

__Panelist__, "Discover UChicago", University of Chicago_ \hfill __2018__

> The _Discover UChicago_ program provides undergraduates with an opportunity to come to the University for a week and learn about campus life and research. At the program's conclusion, current students come to give attendees general advice about professional skills, applying to graduate programs, and selecting mentors and programs.  


# TEACHING AND MENTORING EXPERIENCE \hrulefill


## __Guest Lectures__

Skyline College, __BIOL 230: 	Introduction to Cell Biology: Core II__. _Introduction to Cellular Stress Response_. 13 May 2024.

University of California, Berkeley, __IB 41: Marine Mammals__. _Cancer: A whale of a problem_. 25 October 2023.

University of California, Berkeley, __IB 169: Evolutionary Medicine__. _Evolutionary Dynamics of Cancer I: From Single Cells to Elephants and Whales_. 11 April 2023.

San Jose State University, _A CDKN2C retroduplication in Bowhead whales is associated with the evolution of extremely long lifespans and alerted cell cycle dynamics_. 04 October 2022.

Cal Poly Humboldt, _Resolving the Evolution of Longevity and Associated Traits in Bats Using Functional and Population Genomics_, 10 November 2021.

## Classes

__Organizer and Team Leader__, Cal Summer Genomics Experience. \hfill __Spring 2022__

__Team Leader__, Cal Summer Genomics Experience. \hfill __Spring 2021__

> Organized and ran a pilot experimental field genomics class held over 3 days. 12 students formed teams led by instructors to address unique genetics questions. Students collected samples in the field, then extracted DNA and sequenced genes of interest using Nanopore sequencing.

__Teacher__, Ideal Student Workshop and Test Prep, 8th Grade Class, \hfill __Spring 2019__  
Swift Elementary School.

> Taught a 10-week, 1-hour series on executive life skills, study skills, and practice for taking standardize tests such as the NWEA-MAP exam. Classes were a combination of experiential, game-based learning; group work; and interactive lectures.  


## __Workshops__

__Instructor__, CCB Skills Seminar: _An overview of skills and pipelines for A-Z reproducible manuscripts_. \hfill __11/2023__


__Volunteer Workshop Aide__, StdPopSim Introductory Workshop - Australasia. \hfill __2021__

> Assisted a workshop focused on introducing the StdPopSim Python package for population genetics simulations.

__Organizer__, Mock Interview Prep for Prospective Ph.D. Students, \hfill __01/2021__

> Day-long session for Berkeley undergraduates applying to grad school programs where we provided interview training and preparation, including talks, a workshop, and mock interviews.

__Tutor & Workshop Leader__, Educational Endeavors. \hfill __2016 - 2020__

> Over 670 hours of experience teaching and tutoring students at the high school and undergraduate levels. Tutored in all subjects ranging from STEM fields (Biology, Physical Sciences, Math, Forensics), to language arts (English, Spanish, French) and social sciences (History, Economics) at regular, AP, and collegiate levels. Assisted with and led various tutoring workshops with students from the Daniel Murphy Scholarship Fund and LINK Unlimited.  

__Teaching Assistant__, BIOS 20235 Biological Systems, University of Chicago. \hfill __Winter 2019__

> The second part of the introductory Biology course series for advanced students, focusing on developmental, ecology, and evolutionary biology. In addition to grading and organizing the course, TAs guided discussion sections for students to discuss weekly papers in a collaborative setting.  

__Volunteer Assistant Instructor__, Introduction to Python with Real-World Applications, \hfill __2018__  
Rauner College Prep.

> Taught data science to a class of 12 high school biology students in the context of genomics along with 4 other volunteers.   

__Teaching Assistant__, BIOS 21306 Human Genetics and Evolution, \hfill __Winter 2017__  
University of Chicago.

> Undergraduate course focusing on historic and modern advances in our understanding of human genetics at various scales. In addition to keeping attendance and organizing the course, he taught a lesson on classic and modern techniques for sequencing DNA & RNA; detecting epigenetic modifications in the genome; and on detecting signatures of selection in the genome.  

__Teaching Assistant__, BIOS 21306 Human Genetics and Evolution, \hfill __Winter 2017__  
University of Chicago.

> Undergraduate course focusing on historic and modern advances in our understanding of human genetics at various scales. In addition to keeping attendance and organizing the course, he taught a lesson on classic and modern techniques for sequencing DNA & RNA; detecting epigenetic modifications in the genome; and on detecting signatures of selection in the genome.  

__Laboratory and Lecture Teaching Assistant__, CHM 210H Honors Organic Chemistry Lab, \hfill __Spring 2013__  
University of Rochester.

> Instructor: Joeseph Dinnocenzo. Assisted in the instruction of the lab lecture, lead workshop-style discussions to create the experimental procedures for the labs with students. Oversaw and administered the proper functioning of the lab. Aided and taught students, as well as assessed them for quality work and analytic skills in lab work and in lab reports.  

__Laboratory and Lecture Teaching Assistant__, CHM 173Q Freshman Organic Chemistry Lab, \hfill __Fall 2012__  
University of Rochester.

> Instructor: Bradley Nilsson. Oversaw an organic chemistry lab of 16 freshmen students, grading reports and ensuring the proper functioning of the lab. Ran weekly workshops and lectures for students to design their experiments for the week.  


## __Mentoring__

__Supervisor__, Sarah Gabrielle Villa, B.sc., University of California-Berkeley  \hfill __2023 - Present__

__Group leader__, _Thriving in Science_ Postdoc Support Group \hfill __2020 - 2021__

__Supervisor__, Diana Sam, B.sc., University of California-Berkeley  \hfill __2020 - 2021__

__Supervisor__, Katia Renault, B.sc., University of California-Berkeley \hfill __2020 - 2023__

> PhD Student, Department of Developmental and Regenerative Biology, Harvard University.
> Mentor for 2023 NSF GRFP - Awarded.

__Mentor__, Lily Rahnama, Ph.D., Molecular and Cellular Biology, University of California-Berkeley \hfill __2020 - Present__

__Supervisor__, Nadya Ali, Ph.D, Committee on Evolutionary Biology, University of Chicago \hfill __2018 - 2022__

__Supervisor__, Stephanie E. Bulls, M.S, University of South Alabama. \hfill __2019 - 2020__

__Supervisor__, Eric Chen, B.s, University of Chicago. \hfill __2018 - 2019__

> PhD Student, Department of Developmental and Regenerative Biology, Harvard University
> Mentor for 2019 NSF GRFP - Honorable Mention.


# MEDIA, SERVICE, AND OUTREACH \hrulefill

## __Interviews__

__Neo Life__: Donovan, Robin. "The Salty Secrets of Extreme Longevity." News article. Neo Life, 04/21/2022. https://neo.life/2022/04/the-salty-secrets-of-extreme-longevity/

__Nature__, Career News: Woolston, Chris. "Junior researchers hit by coronavirus-triggered hiring freezes." News article. Nature Career News. Nature, 06/02/2020. https://www.nature.com/articles/d41586-020-01656-3.

__NPR__, Science Friday: Flatow, Ira. "How A ‘Zombie Gene’ Helped Elephants Evolve Protection From Cancer." Audio blog post. Science Friday. NPR, 08/17/2018. https://www.sciencefriday.com/segments/how-a-zombie-gene-helped-elephants-evolve-protection-from-cancer/.  

__CBC News__: Kachur, Torah. "This gene prevents elephants from getting cancer and scientists are taking note." News article. CBC News. CBC, 08/16/2018. https://www.cbc.ca/news/canada/this-gene-prevents-elephants-from-getting-cancer-1.4787721.

__El Español__: Íñiguez De Onzoño, Javier. "El misterioso gen zombi que protege a los elefantes contra el cáncer." News article. El Español. El Español, 08/16/2018. https://www.elespanol.com/ciencia/investigacion/20180815/misterioso-gen-zombi-protege-elefantes-cancer/330218017_0.html.

__Smithsonian Magazine__: Wu, Katherine J. "Cancer Is One Worry Elephants Can Feel Free to Forget." News article. Smithsonian Magazine. The Smithsonian Institute, 08/14/2018. https://www.smithsonianmag.com/science-nature/cancer-one-worry-elephants-forget-180969993/.

## __Public Outreach Events__

__Speaker__: GBatNet My Field for Dummies, "Aging at a Glance: Enabling Age Estimation of Bats." \hfill __2024/08/07__

> Organized by GBatNet, "My Field for Dummies" is a talk series geared towards a general audience on the types of field work bat scientists undertake and its impact.  

__Speaker__: Cientificos en Linea, "De Elefantes y Manatíes: La evolución de resistencia al cáncer en mamíferos gigantes." \hfill __2021/03/16__

> A 30-minute talk for Puerto Rico public TV, geared towards middle/high schoolers with basic biology knowledge as a learning supplement during the COVID-19 pandemic.

__Mentor__, METAS+ Program, Online (Puerto Rico). \hfill __2021 - 2022__

> An NIH-funded, 2-year Mentor-coaching for senior undergrads at the University of Puerto Rico focused on preparing them for the transition to grad school.

__Mentor__, Cientifico Latino, Online (Berkeley, CA). \hfill __2020__

> Provided mentorship and feedback for undergraduate URMs applying to grad programs, and assisted with essays and career planning.

__Organizer__, Merritt Genomics Virtual Lab Tour, Online (Berkeley, CA). \hfill __2020__

> Organized and directed a 90-minute tour of 3 labs virtually, with a showcase of pre-recorded experiments for community college and high school students in Berkeley.

__Speaker__, Merritt Genomics "Scientist Feature" Class Event, Online (Berkeley, CA). \hfill __2020__

> Conversations about my path and life in science with high schoolers and community college students in Berkeley, with an emphasis on career paths

__Volunteer & Organizer__, High School Lab Tours, Department of Human Genetics, University of Chicago. \hfill __2016-2019__

> Organized and assisted with seasonal visits of the lab spaces by students from local, disadvantaged high schools.

__Volunteer Demonstrator & Organizer__, _Science Works_, Museum of Science and Industry, Chicago, IL. \hfill __2016 - 2018__

> _Science Works_ is an event hosted by the Museum of Science and Industry of Chicago that showcases real-life scientists and science to the general public.  
> Alongside other Human Genetics personnel, the team organized and participated in a variety of scientific demonstrations.  

__Volunteer Demonstrator__, _Stand Up for Science_, Field Museum, Chicago, IL. \hfill __2018__

> Organized and participated in various demonstrations, and spoke about science to members of the general public at the Field Museum.  

# CERTIFICATES AND MINI-COURSES \hrulefill

_Torrey Pines Academic Lab Management & Leadership Symposium_, \hfill __Spring 2021__

> 5-day virtual symposium focused on developing a plan for future research labs, from job search to lab management, including staffing, project management, and funding.

_Successfully Managing Your Team of Scientists_, \hfill __Summer 2018__  
University of Chicago myCHOICE program

> 16-hour workshop introducing concepts in team management in industry and academia. Attendees were able to apply knowledge from each session in practical exercises under various scenarios.  

_Introduction to Effective Teaching in STEM_, \hfill __Spring 2018__  
University of Chicago myCHOICE program

> Attendees honed their teaching skills through lectures and practical exercises in this evidence-based pedagogy course.

_Beyond the Bench: The Business of Running a Lab_, \hfill __Fall 2017__  
University of Chicago myCHOICE program.

> A rotating panel of primary investigators and heads of facilities at the University of Chicago taught students every week about the behind-the-scenes work that went into starting and running their labs.  


# PROFESSIONAL MEMBERSHIPS \hrulefill

American Society for Human Genetics \hfill __2024 - __

Society for Molecular Biology and Evolution \hfill __2024 - __

GBatNet \hfill __2022 - __

International Society for Evolution, Medicine, and Public Health \hfill __2022 - __

Western Bat Working Group \hfill __2020 - __

North American Society for Bat Research \hfill __2019 - __

American Aging Association \hfill __2019 - __  

Society for the Advancement of Chicanos/Hispanics and Native Americans in Science \hfill __2018 - __  

American Association for the Advancement of Science \hfill __2015 - 2016__  


# ADDITIONAL SKILLS \hrulefill

__Languages: __ English (native), Spanish (native), French (fluent)

__Programming: __ Python (expert), R (expert), Bash (expert), Julia (novice), Rust (novice)

__DNA & RNA Sequencing: __ short-read (Illumina) and long-read (Oxford Nanopore, PacBio CCS); genome assembly & variant calling

__Epigenetics: __ ChIP-seq (IcE-ChIP, native, and denatured), ATAC-seq, Hi-C, bisulfite-seq

__Single Cell Sequencing: __ 10x Multiome (ATAC+Gene Expression)

__Field Work: __ >800 hours of experience handling bats

___in vivo models: ___ Mice

__Primary Cell Culture__, including primary cell line generation and iPSC generation

__Genetic Engineering__  via CRISPR-_Cas9_ knock-outs

__Microscopy: __ Confocal Microscopy (Leica SP6, SP8); live cell imaging (Olympus Viva View FL)

__Flow Cytometry & FACS: __ Cell-cycle (EdU-Hoescht, Fucci), TUNEL, Flow Karyotyping

__Molecular Biology: __ qPCR; western blot; high molecular weight DNA extraction

__Other skills and interests: __ Sailing, backpacking, guitar, public speaking
